### ISSUE TITLE
OSQuery Logs

### ISSUE THREAD

**Issue by jonny-jhnson** [jsecurity101/Marvel-Lab#13]
OSQuery is currently installed via logging.ps1. Kolide launcher service was created and works. Need to update script to send logs to Splunk.

**Comment by jonny-jhnson** [comment]
Will look at fixing this, this weekend.

**Comment by benjaminshell** [comment]
Logs now being sent to Splunk, fixed in commit dbe9ab0. It requires users to create their own query packs in Fleet. Maybe we can explore adding our own in the future?
