### ISSUE TITLE
Add Olaf's Sysmon Modular Config + Update Sysmon + Add Sysmon TA App

### ISSUE THREAD

**Issue by 4ndr3w6** [jsecurity101/Marvel-Lab#16]
Adding both Olaf's config and App would be a huge bonus to the lab. Additionally, currently for consumed Sysmon events the Splunk process is not being excluded in the inputs.conf. Using the config will help reduce ingested events related to the Splunk process easier, faster, and save licensing resources.

Thanks! :)

**Comment by jonny-jhnson** [comment]
Thanks for the request! Really appreciate the feedback. 

In the future please separate issues/request on a 1:1 basis. This issue contains 2 requests and 1 issue: 

Request 1: Adding both Olaf's config (Done with commit: 8bd3955)

Request 2: Add Olaf's Threat Hunting App. I will create a separate issue for this so I can keep track of progress. This will take some time to figure out the code, but I agree this would be a great addition to this lab. 

Issue 1:  "Additionally, currently for consumed Sysmon events the Splunk process is not being excluded in the inputs.conf." Hopefully Olaf's config fixes this. I looked through it and I believe it will or at least take the majority of the concerns away. If not, feel free to create another issue and I will work on fine tuning it. 

FYI, its probably better to do the exclusions within sysmon config not the inputs.conf. You could do it there, but it is probably easier to do it in the individual telemetry sensor's config. Within the inputs.conf you have to do some ugly regex which is a PITA. I already have some in the current inputs.conf, but want to avoid that when possible. 

Also, Sysmon didn't need to be updated. It pulls the updated version every time `Logging.ps1` is ran

Thanks for the request/issue!
